"""Add Project table

Revision ID: 520e1abc6f5c
Revises: 8af9c0b6a851
Create Date: 2025-12-01 17:36:58.808572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520e1abc6f5c'
down_revision: Union[str, Sequence[str], None] = '8af9c0b6a851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Task', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Task', 'Project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Task', type_='foreignkey')
    op.drop_column('Task', 'project_id')
    op.drop_table('Project')
    # ### end Alembic commands ###
